language: node_js
node_js:
 - "stable"
jobs:
  include:
    - stage: test
      before_install:
        - npm install --progress=false
      script:
        - npm run test -- --coverage
    - stage: deploy
      if: branch = master
      language: generic
      script:
        - apk add --no-cache rsync openssh
        - mkdir -p ~/.ssh
        - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
        - chmod 600 ~/.ssh/id_dsa
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - rsync -rav --delete ./ travis@$SERVER_IP:$APP_PATH
