language: node_js
node_js:
  - stable
jobs:
  include:
    # - stage: test
    #   before_install:
    #     - npm install --progress=false
    #   script:
    #     - npm run test -- --coverage
    - stage: deploy
      if: branch = master
      language: generic
      script:
        - openssl aes-256-cbc -K $encrypted_2a4be346db14_key -iv $encrypted_2a4be346db14_iv -in deploy_key.enc -out ./deploy_key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./deploy_key
        - ssh -i ./deploy_key travis@$SERVER_IP pwd
        # - rsync -rav --delete ./ travis@$SERVER_IP:$APP_PATH
